/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Service.NhanVienService;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;

/**
 *
 * @author Administrator
 */
public class FrmQuanLy extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    NhanVienService nhanVienService = new NhanVienService();
    List<NhanVien> lstNhanVien = nhanVienService.layDanhSachNV();
    int vitri;

    /**
     * Creates new form QlFrm
     */
    public FrmQuanLy() {
        initComponents();
        setLocationRelativeTo(null);

        try {
            //B1 mở luồng <=> tạo đối tượng đọc ghi
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("nhanVien.txt"));
            //B2 thực hiện đọc ghi
            lstNhanVien = (ArrayList<NhanVien>) ois.readObject();  //Thực hiện đọc dữ liệu từ file ra list
            //B3  đong luồng

            ois.close();
            // xử lý khi đọc
            fillToTable();
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Lỗi đọc file");
        }
//        fillToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQLNhanVien = new javax.swing.JLabel();
        plSearch = new javax.swing.JPanel();
        lblIdSearch = new javax.swing.JLabel();
        txtIdSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblStaffName = new javax.swing.JLabel();
        txtStaffName = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        btnImport = new javax.swing.JButton();
        lblArea = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();
        cbbRole = new javax.swing.JComboBox<>();
        cbbArea = new javax.swing.JComboBox<>();
        btnExit = new javax.swing.JButton();
        lblExperience = new javax.swing.JLabel();
        txtExperience = new javax.swing.JTextField();
        btnTop3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQLNhanVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(194, 192, 192));
        setSize(new java.awt.Dimension(645, 690));

        lblQLNhanVien.setBackground(new java.awt.Color(0, 10, 255));
        lblQLNhanVien.setFont(new java.awt.Font("Consolas", 0, 25)); // NOI18N
        lblQLNhanVien.setForeground(new java.awt.Color(0, 10, 255));
        lblQLNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQLNhanVien.setText("QUẢN LÝ NHÂN VIÊN KHÁCH SẠN");
        lblQLNhanVien.setPreferredSize(new java.awt.Dimension(415, 40));

        plSearch.setBackground(new java.awt.Color(174, 196, 221));
        plSearch.setPreferredSize(new java.awt.Dimension(415, 60));

        lblIdSearch.setBackground(new java.awt.Color(0, 0, 0));
        lblIdSearch.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        lblIdSearch.setText("ID");
        lblIdSearch.setPreferredSize(new java.awt.Dimension(36, 18));

        txtIdSearch.setBackground(new java.awt.Color(217, 217, 217));
        txtIdSearch.setPreferredSize(new java.awt.Dimension(230, 30));
        txtIdSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSearchActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setPreferredSize(new java.awt.Dimension(96, 30));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plSearchLayout = new javax.swing.GroupLayout(plSearch);
        plSearch.setLayout(plSearchLayout);
        plSearchLayout.setHorizontalGroup(
            plSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plSearchLayout.setVerticalGroup(
            plSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plSearchLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(plSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(174, 196, 221));
        jPanel2.setPreferredSize(new java.awt.Dimension(575, 315));

        lblId.setBackground(new java.awt.Color(0, 0, 0));
        lblId.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("ID");
        lblId.setPreferredSize(new java.awt.Dimension(90, 21));

        txtId.setBackground(new java.awt.Color(217, 217, 217));
        txtId.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtId.setPreferredSize(new java.awt.Dimension(300, 30));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(9, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblStaffName.setBackground(new java.awt.Color(0, 0, 0));
        lblStaffName.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        lblStaffName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStaffName.setText("Staff's Name");
        lblStaffName.setPreferredSize(new java.awt.Dimension(90, 21));

        txtStaffName.setBackground(new java.awt.Color(217, 217, 217));
        txtStaffName.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtStaffName.setPreferredSize(new java.awt.Dimension(300, 30));
        txtStaffName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffNameActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setPreferredSize(new java.awt.Dimension(90, 30));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lblAge.setBackground(new java.awt.Color(0, 0, 0));
        lblAge.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAge.setText("Age");
        lblAge.setPreferredSize(new java.awt.Dimension(90, 21));

        txtAge.setBackground(new java.awt.Color(217, 217, 217));
        txtAge.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtAge.setPreferredSize(new java.awt.Dimension(300, 30));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDelete.setPreferredSize(new java.awt.Dimension(90, 30));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblRole.setBackground(new java.awt.Color(0, 0, 0));
        lblRole.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole.setText("Role");
        lblRole.setPreferredSize(new java.awt.Dimension(90, 21));

        btnImport.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Documents.png"))); // NOI18N
        btnImport.setText("Import");
        btnImport.setPreferredSize(new java.awt.Dimension(90, 30));
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        lblArea.setBackground(new java.awt.Color(0, 0, 0));
        lblArea.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        lblArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArea.setText("Area");
        lblArea.setPreferredSize(new java.awt.Dimension(90, 21));

        btnExport.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save as.png"))); // NOI18N
        btnExport.setText("Export");
        btnExport.setPreferredSize(new java.awt.Dimension(90, 30));
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        cbbRole.setBackground(new java.awt.Color(217, 217, 217));
        cbbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrators", "Moderators", "Operational", "Regular", "Part-time" }));
        cbbRole.setPreferredSize(new java.awt.Dimension(195, 30));

        cbbArea.setBackground(new java.awt.Color(217, 217, 217));
        cbbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vip", "Classic", "Regular" }));
        cbbArea.setPreferredSize(new java.awt.Dimension(195, 30));

        btnExit.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setPreferredSize(new java.awt.Dimension(90, 30));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblExperience.setBackground(new java.awt.Color(0, 0, 0));
        lblExperience.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        lblExperience.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExperience.setText("experience ");
        lblExperience.setPreferredSize(new java.awt.Dimension(90, 21));

        txtExperience.setBackground(new java.awt.Color(217, 217, 217));
        txtExperience.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtExperience.setPreferredSize(new java.awt.Dimension(300, 30));
        txtExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExperienceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbArea, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(btnImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbbArea, cbbRole});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnDelete, btnEdit, btnExit, btnExport});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbbArea, cbbRole, lblAge, lblArea, lblId, lblRole, lblStaffName, txtAge, txtId});

        btnTop3.setBackground(new java.awt.Color(217, 217, 217));
        btnTop3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnTop3.setForeground(new java.awt.Color(0, 10, 255));
        btnTop3.setText("Top 3 nhân viên có doanh số cao nhất");
        btnTop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTop3ActionPerformed(evt);
            }
        });

        tblQLNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Staff's Name", "Age", "Experience", "Role", "Area", "Salary", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQLNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblQLNhanVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(plSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTop3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTop3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillToTable() {

        if (lstNhanVien == null) {
            JOptionPane.showMessageDialog(this, "Lỗi!");
        } else if (lstNhanVien.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu!");
        } else {
            model = (DefaultTableModel) tblQLNhanVien.getModel();
            model.setRowCount(0);
            for (NhanVien nv : lstNhanVien) {
                double luong = nv.getSalary();
                if (nv.getStatus(nv.getExperience() + "").equalsIgnoreCase("Bán chuyên")) {
                    luong = luong + 75;
                } else if (nv.getStatus(nv.getExperience() + "").equalsIgnoreCase("Chuyên nghiệp")) {
                    luong = luong + 100;
                } else {
                    luong = luong + 200;
                }
                model.addRow(new Object[]{
                    nv.getID(),
                    nv.getName(),
                    nv.getAge(),
                    nv.getExperience(),
                    nv.getRole(),
                    nv.getArea(),
                    luong,
                    nv.getStatus(nv.getExperience() + "")
                });
            }
        }

    }

    private void clearFrom() {
        txtId.setText("");
        txtStaffName.setText("");
        txtAge.setText("");
        txtExperience.setText("");
        cbbRole.setSelectedIndex(0);
        cbbArea.setSelectedIndex(0);
    }

    private void showDetail() {
        NhanVien nv = lstNhanVien.get(vitri);

        txtId.setText(nv.getID());
        txtStaffName.setText(nv.getName());
        txtAge.setText(nv.getAge() + "");
        txtExperience.setText(nv.getExperience() + "");
        cbbRole.setSelectedItem(nv.getRole());
        cbbArea.setSelectedItem(nv.getArea());
    }

    public void addNhanVien() {
        NhanVien nhanVien = new NhanVien();

        nhanVien.setID(txtId.getText());
        nhanVien.setName(txtStaffName.getText());
        nhanVien.setAge(Integer.parseInt(txtAge.getText()));
        nhanVien.setExperience(Integer.parseInt(txtExperience.getText()));
        nhanVien.setRole(cbbRole.getSelectedItem() + "");
        nhanVien.setArea(cbbArea.getSelectedItem() + "");

        lstNhanVien.add(nhanVien);
        model = (DefaultTableModel) tblQLNhanVien.getModel();
    }

    private void txtIdSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSearchActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Thêm phần tử
        fillToTable();
        try {

            if (txtId.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập vào mã nhân viên!");
                txtId.requestFocus();
                return;
            }
            if (txtStaffName.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập vào tên nhân viên!");
                txtStaffName.requestFocus();
                return;
            }
            if (txtAge.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tuổi nhân viên!");
                txtAge.requestFocus();
                return;
            }
            if (txtExperience.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập vào năm kinh nghiệm!");
                txtExperience.requestFocus();
                return;
            }
            //Check tuổi
            try {
                int tuoi = Integer.parseInt(txtAge.getText());
                if (tuoi < 0) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập tuổi là số dương!");
                    txtAge.requestFocus();
                    return;
                }
                if (tuoi < 18) {
                    JOptionPane.showMessageDialog(this, "Chưa đủ tuổi lao động!");
                    txtAge.requestFocus();
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tuổi là số!");
                txtAge.requestFocus();
                return;
            }
            //Check năm kinh nghiệm
            try {
                int namKN = Integer.parseInt(txtExperience.getText());
                if (namKN < 0) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập năm kinh nghiệm lớn hơn hoặc bằng 0!");
                    txtExperience.requestFocus();
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập năm kinh nghiệm là số!");
                txtExperience.requestFocus();
                return;
            }
            //Check trùng id nhân viên
            for (NhanVien nv : lstNhanVien) {
                if (txtId.getText().equals(nv.getID())) {
                    JOptionPane.showMessageDialog(this, "Mã nhân viên " + txtId.getText() + " đã tồn tại!");
                    txtId.requestFocus();
                    return;
                }
            }

            addNhanVien();
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công");
            fillToTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi thêm nhân viên!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtStaffNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffNameActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // Sửa phần tử
        try {
            vitri = tblQLNhanVien.getSelectedRow();
            if (vitri == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần sửa!");
                return;
            }

            NhanVien nv = lstNhanVien.get(vitri);
            nv.setID(txtId.getText());
            nv.setName(txtStaffName.getText());
            nv.setAge(Integer.parseInt(txtAge.getText()));
            nv.setExperience(Integer.parseInt(txtExperience.getText()));
            nv.setRole(cbbRole.getSelectedItem() + "");
            nv.setArea(cbbArea.getSelectedItem() + "");

            JOptionPane.showMessageDialog(this, "Sửa thành công");
            fillToTable();
            tblQLNhanVien.setRowSelectionInterval(vitri, vitri);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi sửa thông tin nhân viên!");

        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Xóa phần tử
        try {
            vitri = tblQLNhanVien.getSelectedRow();
            if (vitri == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xóa!");
                return;
            }
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?");
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            }
            lstNhanVien.remove(vitri);
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            fillToTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi xóa");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // Import: xuất file
        try {
            //B1 mở luồng <=> tạo đối tượng đọc ghi
            ObjectInput ois = new ObjectInputStream(new FileInputStream("nhanVien.txt"));
            //B2 thực hiện đọc ghi
            lstNhanVien = (ArrayList<NhanVien>) ois.readObject();  //Thực hiện đọc dữ liệu từ file ra list
            //B3  đong luồng

            ois.close();
            // xử lý khi đọc
            fillToTable();
            if (lstNhanVien.size() > 0) {
                vitri = 0;
                showDetail();
            } else {
                clearFrom();
            }
            JOptionPane.showMessageDialog(this, "Đọc file thành công");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Lỗi đọc file");
        }
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // Export: lưu list vào file
        try {
            //B1 mở luồng <=> tạo đối tượng đọc ghi
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("nhanVien.txt"));
            //B2 thực hiện đọc ghi
            oos.writeObject(lstNhanVien); // ghi listHocSinh vào file

            //B3  đong luồng
            oos.flush();
            oos.close();
            JOptionPane.showMessageDialog(this, "Ghi thành công");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Lỗi ghi file");
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Thoát
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn lưu lại dữ liệu hiện tại không?");
        if (hoi != JOptionPane.YES_OPTION) {
            this.dispose();
        } else {
            try {
                ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("nhanVien.txt"));
                //B2 thực hiện đọc ghi
                oos.writeObject(lstNhanVien); // ghi listHocSinh vào file

                //B3  đong luồng
                oos.flush();
                oos.close();
                JOptionPane.showMessageDialog(this, "Lưu dữ liệu thành công");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi lưu dữ liệu!");
            }

        }
        new FrmDangNhap(null, false).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // Tìm nhân viên theo ID
        try {
            String idSearch = txtIdSearch.getText();
            if (idSearch.equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập vào mã nhân viên cần tìm!");
                txtIdSearch.requestFocus();
                return;
            }
            int count = 0;
            for (NhanVien nv : lstNhanVien) {
                if (nv.getID().equals(idSearch)) {
                    JOptionPane.showMessageDialog(this, "Tìm thấy nhân viên có mã: " + idSearch);
                    vitri = lstNhanVien.indexOf(nv);
                    tblQLNhanVien.setRowSelectionInterval(vitri, vitri);
                    showDetail();
                    count++;
                    break;
                }
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên có mã: " + idSearch);
                txtIdSearch.requestFocus();
                clearFrom();
                tblQLNhanVien.clearSelection();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tìm nhân viên!");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExperienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExperienceActionPerformed

    private void btnTop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTop3ActionPerformed
        // Top 3 nhân viên có doanh số cao nhất
        Collections.sort(lstNhanVien, (o1, o2) -> {
            return o1.getSalary() > o2.getSalary() ? 1 : -1;
        }); 
        Collections.reverse(lstNhanVien);
        model = (DefaultTableModel) tblQLNhanVien.getModel();
        model.setRowCount(0);
        for (NhanVien nv : lstNhanVien) {
            double luong = nv.getSalary();
            if (nv.getStatus(nv.getExperience() + "").equalsIgnoreCase("Bán chuyên")) {
                luong = luong + 75;
            } else if (nv.getStatus(nv.getExperience() + "").equalsIgnoreCase("Chuyên nghiệp")) {
                luong = luong + 100;
            } else {
                luong = luong + 200;
            }
            model.addRow(new Object[]{
                nv.getID(),
                nv.getName(),
                nv.getAge(),
                nv.getExperience(),
                nv.getRole(),
                nv.getArea(),
                luong,
                nv.getStatus(nv.getExperience() + "")
            });
            if(model.getRowCount() == 3){
                break;
            }
        }
    }//GEN-LAST:event_btnTop3ActionPerformed

    private void tblQLNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLNhanVienMouseClicked
        // show
        vitri = tblQLNhanVien.getSelectedRow();
        showDetail();
    }//GEN-LAST:event_tblQLNhanVienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTop3;
    private javax.swing.JComboBox<String> cbbArea;
    private javax.swing.JComboBox<String> cbbRole;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblExperience;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdSearch;
    private javax.swing.JLabel lblQLNhanVien;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblStaffName;
    private javax.swing.JPanel plSearch;
    private javax.swing.JTable tblQLNhanVien;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdSearch;
    private javax.swing.JTextField txtStaffName;
    // End of variables declaration//GEN-END:variables
}
